-- CreateTable
CREATE TABLE `Flight` (
  `id` VARCHAR(191) NOT NULL,
  `airline` VARCHAR(191) NOT NULL,
  `from` VARCHAR(191) NOT NULL,
  `to` VARCHAR(191) NOT NULL,
  `departure` DATETIME(3) NOT NULL,
  `arrival` DATETIME(3) NOT NULL,
  `duration` VARCHAR(191) NOT NULL,
  `stops` INTEGER NOT NULL,
  `price` INTEGER NOT NULL,
  `fareClass` VARCHAR(191) NOT NULL,
  `amenities` JSON NOT NULL,
  `market` VARCHAR(191) NOT NULL,
  `region` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Hotel` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `location` VARCHAR(191) NOT NULL,
  `pricePerNight` INTEGER NOT NULL,
  `rating` DOUBLE NOT NULL,
  `amenities` JSON NOT NULL,
  `market` VARCHAR(191) NOT NULL,
  `images` JSON NOT NULL,
  `gallery` JSON NOT NULL,
  `description` LONGTEXT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BusRoute` (
  `id` VARCHAR(191) NOT NULL,
  `operator` VARCHAR(191) NOT NULL,
  `route` VARCHAR(191) NOT NULL,
  `departure` DATETIME(3) NOT NULL,
  `arrival` DATETIME(3) NOT NULL,
  `duration` VARCHAR(191) NOT NULL,
  `price` INTEGER NOT NULL,
  `amenities` JSON NOT NULL,
  `seating` VARCHAR(191) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `market` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HolidayPackage` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `destination` VARCHAR(191) NOT NULL,
  `theme` VARCHAR(191) NOT NULL,
  `duration` VARCHAR(191) NOT NULL,
  `pricePerPerson` INTEGER NOT NULL,
  `travelersIncluded` INTEGER NOT NULL,
  `highlights` JSON NOT NULL,
  `description` LONGTEXT NOT NULL,
  `market` VARCHAR(191) NOT NULL,
  `gallery` JSON NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
  `id` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `password` VARCHAR(191) NOT NULL,
  `tier` VARCHAR(191) NOT NULL,
  `role` VARCHAR(191) NOT NULL,
  `points` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `User_email_key`(`email`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
